services:
  web:
    build: .
    image: mangoteka:latest
    container_name: mangoteka
    ports:
      - "${WEB_PORT:-8765}:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      MANGOTEKA_HOST: "0.0.0.0"
      MANGOTEKA_PORT: "8000"
      MANGOTEKA_DATA: "/data"
